[gemini]
api_key = "AIzaSyALpybT2IbcCv0kQNNTM4bu6nmmUGK1nvQ"

[google_maps]
api_key = "AIzaSyDQLoLnPK9dUsQjDfkz5wVa3uTr1NZ45wg"

[geoapify]
api_key = "66dc990bf2034af492426db6e999e6ec"

[mapbox]
access_token = "pk.d10ff2dc933cd43aa288a40a518f5406"

[mapmyindia]
api_key = "xxhsfxawdhmwwypfgywszkviqbblzgijugfa"
